name: gh-action-test

on:
  push:
    branches:
      - master         # Push events on master branch
      - 'releases/**'  # Push events to branches matching refs/heads/releases/10
      # Sequence of patterns matched against refs/tags
    tags:        
      - v1             # Push events to v1 tag
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      working-directory: server
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
